name: E2E Tests - Reusable

on:
  workflow_call:
    secrets:
      access-token:
        required: true

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          repository: puremike/gh-actions
          ref: main
          token: ${{secrets.access-token || secrets.GITHUB_TOKEN}}
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: Install dependencies
        run: npm ci
      - name: Run E2E tests
        run: npm run test:e2e
